export { SingInPage } from './sing-in-page'
export { SingUpPage } from './sing-up-page'
export { ForgotPasswordPage } from './forgot-password-page'
export { NewPasswordPage } from './new-password-page'
export { CheckEmailPage } from './check-email-page'
